# Generated by Django 3.0.7 on 2020-06-28 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
